//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeDbUtil.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class BESystemColors
    {
        public string SysButtonBG { get; set; }
        public string SysButtonRollOv { get; set; }
        public string SysBGColor { get; set; }
        public string HolidayBGColor { get; set; }
        public string SysRptBGBarColor { get; set; }
        public string SysRptGrandTotColor { get; set; }
        public string SysRptSubTotColor { get; set; }
        public string SysFormHeadBGColor { get; set; }
        public string SysMenuColor { get; set; }
        public string SysRollOverColor { get; set; }
        public string SysAgendaHdrColor { get; set; }
        public string SysTabBGColor { get; set; }
        public string TentativeColor { get; set; }
        public string SpeakerInvitedColor { get; set; }
        public string ConfirmedColor { get; set; }
        public string SpeakerDeclinedColor { get; set; }
        public string CancelledColor { get; set; }
        public string SysChartSeries1 { get; set; }
        public string SysChartSeries2 { get; set; }
        public string SysChartSeries3 { get; set; }
        public string SysChartBGColor { get; set; }
        public string SysChartFontColor { get; set; }
        public string SysGradientStart { get; set; }
        public string SysGradientEnd { get; set; }
        public string MenuBar { get; set; }
        public string MenuBarFont { get; set; }
        public string MenuDDBackground { get; set; }
        public string DashboardBackground { get; set; }
    }
}
